Board: {
  shape: class

  -id
  -title
  -content
  -createDate
  -commentList
}

Comment: {
  shape: class

  -id
  -title
  -content
  -createDate
  -board
}

BoardService : {
  shape : class

  getList() : List<Board>
  getBoard(id) : board
}