shape: sequence_diagram
con: Controller
ser: Service
rep: Repository

getList: {
  con -> ser
  ser -> rep
  rep -> ser
  ser -> con
}

detail: {
  con -> ser : id
  ser -> rep
  rep -> ser
  ser -> con : model, id, form
}

create: {
  con -> ser : form
  ser -> rep
  rep -> ser
  ser -> con
}